CREATE TABLE CENTER_BOARD (
  seq 		INTEGER PRIMARY KEY,
  title 	VARCHAR(255) NOT NULL ,
  content 	VARCHAR(1000) NOT NULL ,
  writer 	VARCHAR(20) NOT NULL ,
  password	VARCHAR(10) NOT NULL ,
  regDate 	DATE NOT NULL ,
  cnt 		INTEGER NOT NULL
);